#!/usr/bin/env tsx
/**
 * CSS Token Generator
 *
 * Reads design-system/tokens.ts and generates the :root {} block
 * in app/globals.css between marker comments.
 *
 * Usage:
 *   npm run tokens          # generate
 *   npm run tokens:check    # check if globals.css is up to date
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { tokens } from "./tokens";
import { tokenKeyToCssVar, sidebarKeyToCssVar } from "./utils";

const GLOBALS_PATH = resolve(__dirname, "../app/globals.css");
const START_MARKER =
  "/* === GENERATED BY design-system/generate-css.ts — DO NOT EDIT === */";
const END_MARKER = "/* === END GENERATED === */";

function generateRootBlock(): string {
  const lines: string[] = [];
  lines.push(START_MARKER);
  lines.push("/* GrooveShelf Dark Theme — vinyl store aesthetic */");
  lines.push(":root {");

  // Colors
  for (const [key, value] of Object.entries(tokens.colors)) {
    lines.push(`  ${tokenKeyToCssVar(key)}: ${value};`);
  }

  // Radius
  lines.push(`  --radius: ${tokens.radius};`);

  // Sidebar
  for (const [key, value] of Object.entries(tokens.sidebar)) {
    lines.push(`  ${sidebarKeyToCssVar(key)}: ${value};`);
  }

  lines.push("}");
  lines.push(END_MARKER);

  return lines.join("\n");
}

function run() {
  const isCheck = process.argv.includes("--check");
  const css = readFileSync(GLOBALS_PATH, "utf-8");
  const generated = generateRootBlock();

  // Check if markers exist
  const hasMarkers =
    css.includes(START_MARKER) && css.includes(END_MARKER);

  let newCss: string;

  if (hasMarkers) {
    // Replace between markers
    const startIdx = css.indexOf(START_MARKER);
    const endIdx = css.indexOf(END_MARKER) + END_MARKER.length;
    newCss = css.slice(0, startIdx) + generated + css.slice(endIdx);
  } else {
    // Find existing :root block and wrap it
    const rootRegex =
      /\/\*\s*GrooveShelf Dark Theme[^*]*\*\/\s*:root\s*\{[^}]*\}/;
    const match = css.match(rootRegex);

    if (match) {
      newCss = css.replace(match[0], generated);
    } else {
      // Fallback: just replace any :root block
      const simpleRootRegex = /:root\s*\{[^}]*\}/;
      const simpleMatch = css.match(simpleRootRegex);
      if (simpleMatch) {
        newCss = css.replace(simpleMatch[0], generated);
      } else {
        console.error("Could not find :root block in globals.css");
        process.exit(1);
      }
    }
  }

  if (isCheck) {
    if (newCss === css) {
      console.log("✅ globals.css is up to date with tokens.ts");
      process.exit(0);
    } else {
      console.error(
        "❌ globals.css is out of sync with tokens.ts. Run: npm run tokens"
      );
      process.exit(1);
    }
  }

  writeFileSync(GLOBALS_PATH, newCss, "utf-8");
  console.log("✅ Generated app/globals.css from design-system/tokens.ts");
}

run();
